python main.py \
--model_name_or_path gpt2 \
--config_name gpt2 \
--tokenizer_name gpt2 \
--dataset_name daily_dialog \
--overwrite_cache \
--cache_dir cache/ \
--train_batch_size 8 \
--val_batch_size 8 \
--gradient_accumulation_steps 2 \
--n_epochs 5 \
--num_training_steps 5000 \
--warmup_steps 2000 \
--learning_rate 5e-5 \
--checkpoint_interval 1000 \
--validation_interval 1000 \
--n_gpu 1 