python main.py \
--model_name_or_path gpt2 \
--config_name gpt2 \
--tokenizer_name gpt2 \
--dataset_name daily_dialog \
--cache_dir cache \
--output_dir output \
--per_gpu_train_batch_size 8 \
--per_gpu_eval_batch_size 8 \
--evaluation_strategy epoch \
--gradient_accumulation_steps 2 \
--fp16 False \
--num_train_epochs 5 \
--warmup_steps 2000 \
--report_to neptune